### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [jhollist/lakemorpho#18]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by jsta** [comment]
Thinking about taking a run at this @jhollist (or at least determining how big a job it will be). Are you in-process?

**Comment by jhollist** [comment]
@jsta I am not in process at all, so if you have the bandwidth I would be VERY happy to have you take a crack at it. 

I have some other ideas about re-working lakemorpho, but those are maybe a bigger effort.  

After you've assessed how much work this would be, we should chat and think about what the next iteration of lakemorpho would look like.  

Thanks!

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023. https://github.com/jhollist/elevatr/issues/77 https://github.com/jhollist/quickmapr/issues/26

**Comment by rsbivand** [comment]
@jsta @jhollist  See also https://r-spatial.org/r/2023/05/15/evolution4.html. Please take urgent steps to resolve this issue. No positive changes appear in the repository. Less than three months remain to retain this package on CRAN.

**Comment by jhollist** [comment]
Fixed and on CRAN.  Thanks!
