### ISSUE TITLE
Add calculation of Fourier coefficients?

### ISSUE THREAD

**Issue by jsta** [jhollist/lakemorpho#7]
I volunteered to review this paper for JOSS: https://github.com/sgrieve/spatial_efd

I think using this technique to calculate lake Fourier coefficients could be very useful!

**Comment by jhollist** [comment]
Thats pretty cool.  I do see the utility for lakes, but it feels more like a general purpose spatial tool than something specific to lake morphometry.  My gut reaction is that a separate package (or maybe part of another package) for doing this would be the way to go initially.

**Comment by jsta** [comment]
Makes sense. I plan to investigate and report back if I find it to be useful.
